version: '3.8'

volumes:
    prometheus_data: {}

services:
  prometheus:
      image: prom/prometheus
      container_name: prokutindv-netology-prometheus
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus/alert.rules:/etc/prometheus/alert.rules 
        - ./prometheus:/etc/prometheus
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      networks:
        - prokutindv-my-netology-hw
      restart: always
      links:
      - pushgateway:pushgateway
      depends_on:
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    container_name: prokutindv-netology-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
        - prokutindv-my-netology-hw
    restart: always
    

networks:
  prokutindv-my-netology-hw:  
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16