version: '3.8'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  pushgateway:
    image: prom/pushgateway
    container_name: prokutindv-netology-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - prokutindv-my-netology-hw
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prokutindv-netology-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - prokutindv-my-netology-hw
    restart: unless-stopped
    links:
      - pushgateway:pushgateway
    depends_on:
      - pushgateway
  grafana:
    image: grafana/grafana
    container_name: prokutindv-netology-grafana
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - prokutindv-my-netology-hw
    restart: unless-stopped

networks:
  prokutindv-my-netology-hw:
    external: true
    name: prokutindv-my-netology-hw
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16